classDiagram
    class PlantRecord {
    }

    class Identification {
        scientific_name: Primary scientific name of the plant
        common_names: List of common names
        common_name: Primary common name
        rank: Taxonomic rank
        genus: Genus name
        family: Family name
        family_common_name: Common name of the family
        synonyms: Alternative scientific names
        year: Year of scientific description
        author: Author of the scientific name
        bibliography: Reference documentation
    }

    class Appearance {
        flower_color: Color of the flowers
        flower_conspicuous: Whether flowers are noticeable
        foliage_color: Color of the leaves
        foliage_texture: Texture of the leaves
        fruit_color: Color of the fruit
        fruit_conspicuous: Whether fruit is noticeable
        average_height_cm: Average height in centimeters
        maximum_height_cm: Maximum height in centimeters
    }

    class Growth {
        growth_habit: General growth pattern
        growth_form: Form of growth
        growth_rate: Speed of growth
        growth_months: Months when active growth occurs
        bloom_months: Months when flowering occurs
        fruit_months: Months when fruit is present
    }

    class Cultivation {
        edible: Whether any part is edible
        edible_part: Which parts can be eaten
        vegetable: Whether considered a vegetable
        planting_days_to_harvest: Days from planting to harvest
        planting_description: General planting instructions
        planting_sowing_description: Specific sowing instructions
        planting_row_spacing_cm: Space between rows in cm
        planting_spread_cm: Spread of plant in cm
        minimum_root_depth_cm: Minimum soil depth needed
    }

    class Environment {
        humidity: Air humidity requirements
        ground_humidity: Soil moisture requirements
        light: Light level requirements
        soil_nutriments: Soil fertility requirements
        soil_salinity: Salt tolerance in soil
        anaerobic_tolerance: Tolerance to poor soil aeration
        ph_maximum: Maximum suitable soil pH
        ph_minimum: Minimum suitable soil pH
        distributions: Geographic distribution areas
    }

    class References {
        image_url: URL to plant image
        wiki_url: Wikipedia article URL
        url_usda: USDA database link
        url_tropicos: Tropicos database link
        url_tela_botanica: Tela Botanica reference
        url_powo: Plants of the World Online link
        url_plantnet: PlantNet database link
        url_gbif: Global Biodiversity Facility link
        url_openfarm: OpenFarm growing guide
        url_catminat: Catminat database reference
    }

    PlantRecord -- Identification
    PlantRecord -- Appearance
    PlantRecord -- Growth
    PlantRecord -- Cultivation
    PlantRecord -- Environment
    PlantRecord -- References
